### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [munroeka/prj-rev-bwfs-dasmoto#3]
Your CSS is looking pretty good, but one thing that I always recommend is to review your CSS at the end to see what properties can be removed, especially for ones that are duplicates in many places.  This technique is referred to as DRY (don't repeat yourself) and results in much more extensible and maintainable code for the future.  There are many techniques to make your code DRY such as creating a single class that you can repeat throughout your CSS, using combo selectors, or moving common styles into more broadly assigned selectors (such as `body` or `html`).

In this case, we could make your CSS more dry by using a combo selector for `font-family` and removing some unnecessary properties due to default styles (e.g. `font-weight` in your heading selectors).  Here is an example.

``` css
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}

h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

.item h2 {
  font-size: 32px;
  color: white;
}

.price {
  font-weight: bold;
  color: blue;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

Notice also in this example I am restricting the `h2` style to only headings that are within each of my items.  You did a great job wrapping a container around each item in your HTML, so since you took the trouble to do this I would recommend just giving those components a name as well (e.g. I called them `item`).

https://github.com/munroeka/prj-rev-bwfs-dasmoto/blob/a3629fba66621bd0649bb563dcff5c15b9f0a31a/DasArts%26Crafts/arts_crafts.html#L12-L21
